var TESTS = {
	"testPages":
	[
		"autodivider",
		"button",
		"check",
		"collapsible",
		"datetimepicker",
		"fastscroll",
		"gallery",
		"handler",
		"headerfooter",
		"list",
		"listdividers",
		/*"multimediaview",*/
		"navigationbar",
		"notification",
		"popup",
		"progressbar",
		"radio",
		"searchbar",
		"segmentcontrol",
		"slider",
		"swipe",
		"tabbar",
		"toggleswitch",
		"tokentextarea",
		"virtuallist",
		"virtualgrid",
	]
};