WatchOnSandbox( "STMS", function( m ) {
var STMS = m.STMS,
map = {
IDS_ST_BODY_VOLUME_M_SOUND_ABB: "Сила звук",
IDS_SR_BODY_AIR_CONDITIONER: "Климатик",
IDS_SR_BODY_AUSTRIA_M_COUNTRYNAME: "Австрия",
IDS_SR_BODY_BELGIUM_M_COUNTRYNAME: "Белгия",
IDS_SR_BODY_CHINA_M_COUNTRYNAME: "Китай",
IDS_SR_BODY_DENMARK_M_COUNTRYNAME: "Дания",
IDS_SR_BODY_FAN_SPEED_DOWN: "Намаляване на вентилатора",
IDS_SR_BODY_FAN_SPEED_UP: "Ускоряване на вентилатора",
IDS_SR_BODY_FINLAND_M_COUNTRYNAME: "Финландия",
IDS_SR_BODY_FRANCE_M_COUNTRYNAME: "Франция",
IDS_SR_BODY_GERMANY_M_COUNTRYNAME: "Германия",
IDS_SR_BODY_IRELAND_M_COUNTRYNAME: "Ирландия",
IDS_SR_BODY_ITALY_M_COUNTRYNAME: "Италия",
IDS_SR_BODY_LUXEMBOURG_M_COUNTRYNAME: "Люксембург",
IDS_SR_BODY_MODE: "Режим",
IDS_SR_BODY_NORWAY_M_COUNTRYNAME: "Норвегия",
IDS_SR_BODY_POLAND_M_COUNTRYNAME: "Полша",
IDS_SR_BODY_PORTUGAL_M_COUNTRYNAME: "Португалия",
IDS_SR_BODY_SET_UP: "Настройване",
IDS_SR_BODY_SOUTH_KOREA_M_COUNTRYNAME: "Южна Корея",
IDS_SR_BODY_SPAIN_M_COUNTRYNAME: "Испания",
IDS_SR_BODY_SWEDEN_M_COUNTRYNAME: "Швеция",
IDS_SR_BODY_SWITZERLAND_M_COUNTRYNAME: "Швейцария",
IDS_SR_BODY_UNITED_KINGDOM_M_COUNTRYNAME: "Великобритания",
IDS_SR_BODY_UNITED_STATES_OF_AMERICA_M_COUNTRYNAME: "Съединени американски щати",
IDS_SR_BUTTON_BACK: "Назад",
IDS_SR_BUTTON_CANCEL_ABB: "Отказ",
IDS_SR_BUTTON_DELETE: "Изтрий",
IDS_SR_BUTTON_DONE: "Готово",
IDS_SR_BUTTON_EXIT: "Изход",
IDS_SR_BUTTON_INFO: "Информ.",
IDS_SR_BUTTON_MENU: "Меню",
IDS_SR_BUTTON_MUTE: "Загл.",
IDS_SR_BUTTON_OK: "OK",
IDS_SR_BUTTON_POWER: "Вкл/изкл",
IDS_SR_BUTTON_SELECT_YOUR_COUNTRY: "Изберете държавата си",
IDS_SR_BUTTON_SELECT_YOUR_COUNTRY_REGION: "Изберете държавата/региона си",
IDS_SR_BUTTON_SHOW_OTHER_BRANDS: "Показване на други марки",
IDS_SR_BUTTON_SOURCE_T_SMART_REMOTE: "Източник",
IDS_SR_BUTTON_TEMP_DOWN_M_TEMPERATURE: "Темп. над.",
IDS_SR_BUTTON_TEMP_UP_M_TEMPERATURE: "Темп. наг.",
IDS_SR_BUTTON_TV: "ТВ",
IDS_SR_BUTTON_YES: "Да",
IDS_SR_HEADER_ALL_BRANDS: "Всички марки",
IDS_SR_HEADER_DELETE_ABB: "Изтриване",
IDS_SR_HEADER_RESET: "Нyлиране",
IDS_SR_HEADER_WATCHON_M_APPLICATION: "WatchON",
IDS_SR_OPT_ADD_DEVICE_ABB: "Добав. устройство",
IDS_SR_OPT_STB_ABB: "Цифр. у-во",
IDS_YSM_POP_SET_UP_THE_REMOTE_CONTROL_ON_YOUR_DEVICE_Q: "Искате ли да настроите дистанционното управление на вашето устройство?",
IDS_YSM_OPT_SHOW_ALL_BRANDS_ABB: "Показване на всички марки",
IDS_YSM_BUTTON_VOL_UC: "ЗВУК",
IDS_YSM_BUTTON_CH: "КАН",
IDS_YSM_BUTTON_NO: "Не",
IDS_SAPPS_BODY_NOTICE: "Известие",
IDS_MSGF_HEADER_OPTION: "Опция",
IDS_MSGF_HEADER_OPTIONS: "Опции",
IDS_SSCHOL_HEADER_COMPLETED: "Завършено",
IDS_YSM_HEADER_SET_UP_REMOTE_ABB: "Настр. дистанц.",
IDS_YSM_BODY_SET_UP_THE_REMOTE_CONTROL_ON_YOUR_DEVICE_Q: "Искате ли да настроите дистанционното управление на вашето устройство?",
IDS_YSM_BODY_LATIN_COUNTRIES_ABB: "Латиноамерикански страни",
IDS_YSM_BODY_POINT_YOUR_WATCH_TOWARDS_THE_PS_AND_TAP_THE_POWER_BUTTON: "Насочете часовника си към %s и натиснете бутона за включване.",
IDS_YSM_BODY_TAP_THE_BUTTON_ABB: "Чукнете бутона.",
IDS_YSM_BODY_DID_IT_WORK_Q_ABB: "Проработи ли?",
IDS_YSM_HEADER_SETUP_COMPLETE_ABB: "Настр. завърши",
IDS_YSM_BODY_PS_REMOTE_CONTROL_SETUP_IS_COMPLETE: "Настройването на универсално дистанционно управление %s завърши.",
IDS_YSM_BODY_THIS_MODEL_IS_NOT_SUPPORTED: "Този модел не се поддържа.",
IDS_YSM_BODY_THE_REMOTE_CONTROL_WILL_BE_REMOVED: "Дистанционното управление ще бъде премахнато.",
IDS_YSM_BODY_FAN_SPEED_ABB: "Ск. вент.",
IDS_YSM_BODY_MODE_ABB2: "Режим",
IDS_YSM_OPT_AV_RECEIVER_ABB2: "AV приемник",
IDS_YSM_BODY_BLUE: "Син",
IDS_YSM_BODY_CHANNEL_DOWN_ABB: "Предишен канал",
IDS_YSM_BODY_CHANNEL_LIST_ABB: "Спис. с канали",
IDS_YSM_BODY_CHANNEL_UP_ABB: "Следващ канал",
IDS_YSM_BODY_DISK_MENU_ABB: "Меню на диска",
IDS_YSM_BODY_DOWN: "Надолу",
IDS_YSM_BODY_DVR: "DVR",
IDS_YSM_BODY_EJECT_ABB: "Изваждане",
IDS_YSM_BODY_FAST_FORWARD_ABB: "Бързо напред",
IDS_YSM_BODY_FAVOURITE_ABB: "Предпочитано",
IDS_YSM_BODY_FORMAT_HASPECT_ABB: "Формат (съотн.)",
IDS_YSM_BODY_GREEN_ABB: "Зелено",
IDS_YSM_BODY_HDMI_PD_ABB: "HDMI %d",
IDS_YSM_BODY_INPUT_ABB: "Въвеждане",
IDS_YSM_BODY_LEFT: "Отляво",
IDS_YSM_BODY_LIST: "Списък",
IDS_YSM_BODY_OTHER_COUNTRIES_ABB: "Други страни",
IDS_YSM_BODY_PAUSE: "Пауза",
IDS_YSM_BODY_PLAY: "Изпълняване",
IDS_YSM_BODY_PREVIOUS: "Предишен",
IDS_YSM_BODY_PRE_CHANNEL_ABB: "Пред. канал",
IDS_YSM_BODY_RED: "Червен",
IDS_YSM_BODY_REWIND_ABB: "Пренавиване",
IDS_YSM_BODY_RIGHT_ABB2: "Отдясно",
IDS_YSM_BODY_SELECT: "Избор",
IDS_YSM_BODY_SOUND_MODE_ABB: "Режим на звука",
IDS_YSM_BODY_START_SETUP_OF_STB_REMOTE_CONTROL: "За стартиране на настройката на дистанционно у-ние за цифрово у-во.",
IDS_YSM_BODY_STOP: "Спри",
IDS_YSM_BODY_SUBTITLES_ABB2: "Субтитри",
IDS_YSM_BODY_SUBWOOFER_ABB: "Събуфер",
IDS_YSM_BODY_SURROUND_ABB: "Съраунд",
IDS_YSM_BODY_TITLE_MENU_ABB: "Заглавно меню",
IDS_YSM_BODY_UP: "Нагоре",
IDS_YSM_BODY_YELLOW_ABB: "Жълто",
IDS_YSM_BUTTON_CLEAR_HISTORY_ABB: "Изтриване хронол.",
IDS_YSM_BUTTON_DONE: "Готово",
IDS_YSM_BUTTON_HISTORY: "Хронология",
IDS_YSM_BUTTON_MENU: "Меню",
IDS_YSM_BUTTON_NEXT: "Следващ",
IDS_YSM_BUTTON_RETURN_UC: "ВРЪЩАНЕ",
IDS_YSM_BUTTON_SMART_HUB: "Smart Hub",
IDS_YSM_BUTTON_TOOLS_UC: "ИНСТРУМЕНТИ",
IDS_YSM_BUTTON_VIDEO: "Видео",
IDS_YSM_BUTTON_VOD: "VOD",
IDS_YSM_HEADER_HELP: "Помощ",
IDS_YSM_OPT_0: "0",
IDS_YSM_OPT_1: "1",
IDS_YSM_OPT_2: "2",
IDS_YSM_OPT_3: "3",
IDS_YSM_OPT_4: "4",
IDS_YSM_OPT_5: "5",
IDS_YSM_OPT_6: "6",
IDS_YSM_OPT_7: "7",
IDS_YSM_OPT_8: "8",
IDS_YSM_OPT_9: "9",
IDS_YSM_OPT_ENTER: "Влез",
IDS_YSM_OPT_POWER: "Вкл./Изкл.",
IDS_YSM_OPT_RECORD: "Запис",
IDS_YSM_OPT_VOLUME_DOWN: "Намаляване на силата на звука",
IDS_YSM_OPT_VOLUME_UP: "Увеличаване на силата на звука",
IDS_YSM_TAB4_GUIDE: "Справочник",
IDS_CHATON_BODY_INDIA_M_COUNTRYNAME: "Индия",
IDS_CHATON_BODY_NETHERLANDS_M_COUNTRYNAME: "Нидерландия",
IDS_WCL_BODY_RUSSIA_M_COUNTRYNAME: "Русия",
IDS_CHATON_BODY_AUSTRALIA_M_COUNTRYNAME: "Австралия",
IDS_CHATON_BODY_SAUDI_ARABIA_M_COUNTRYNAME: "Саудитска Арабия",
IDS_CHATON_BODY_CANADA_M_COUNTRYNAME: "Канада",
IDS_CHATON_BODY_BRAZIL_M_COUNTRYNAME: "Бразилия",
IDS_CHATON_BODY_MEXICO_M_COUNTRYNAME: "Мексико",
IDS_CHATON_BODY_ARGENTINA_M_COUNTRYNAME: "Аржентина",
IDS_CHATON_BODY_CHILE_M_COUNTRYNAME: "Чили",
IDS_CHATON_BODY_PERU_M_COUNTRYNAME: "Перу",
IDS_CHATON_BODY_COLOMBIA_M_COUNTRYNAME: "Колумбия",
IDS_COM_POP_TRY_AGAIN: "Нов опит",
IDS_YSM_BODY_CHANGE_DEVICE_M_NOUN_ABB: "Пром. на у-во",
IDS_YSM_BODY_TEMP_M_TEMPERATURE_ABB: "Темп.",
IDS_MSGF_BODY_REMOTE: "Дистанционно",
IDS_YSM_OPT_TEMP_DOWN_ABB: "Температ. надолу",
IDS_YSM_OPT_TEMP_UP_ABB: "Температ. нагоре",
IDS_YSM_OPT_TURBO_ABB: "Турбо",
IDS_YSM_OPT_DISPLAY_ABB: "Дисплей",
IDS_YSM_OPT_DELIMITER_ABB: "Разделител",
IDS_YSM_OPT_INTERNET_ABB: "Интернет",
IDS_YSM_OPT_PIP: "PiP",
IDS_YSM_OPT_PIP_SWAP_ABB: "PiP размяна",
IDS_YSM_OPT_PIP_CHANNEL_MINUS_ABB: "PiP канал -",
IDS_YSM_OPT_PIP_CHANNEL_PLUS_ABB: "PiP канал +",
IDS_YSM_OPT_PIP_MOVE_ABB: "PiP преместване",
IDS_YSM_OPT_DTV: "DTV",
IDS_YSM_OPT_COMPONENT_PD_ABB: "Компонент %d",
IDS_YSM_OPT_USB: "USB",
IDS_YSM_OPT_PICTURE_ABB2: "Картина",
IDS_YSM_OPT_3D: "3d",
IDS_YSM_OPT_REPLAY_ABB: "Пускане отново",
IDS_YSM_OPT_DAY_MINUS: "Ден -",
IDS_YSM_OPT_DAY_PLUS: "Ден +",
IDS_YSM_OPT_RADIO: "Радио",
IDS_YSM_OPT_TV_RADIO_ABB: "ТВ/радио",
IDS_YSM_OPT_SWING_DOWN_ABB: "Залюлейте надолу",
IDS_YSM_OPT_SWING_LEFT_ABB: "Залюлейте наляво",
IDS_YSM_OPT_SWING_RIGHT_ABB: "Залюл. надясно",
IDS_YSM_OPT_SWING_UP_ABB: "Залюлейте нагоре",
IDS_YSM_OPT_PVR_MENU_ABB: "PVR меню",
IDS_YSM_OPT_RETURN_TO_LIVE_ABB: "Вр. към На живо",
IDS_YSM_OPT_POWER_OFF_ABB2: "Изключване",
IDS_YSM_OPT_POWER_ON_ABB: "Включване",
IDS_CHATON_BODY_JAPAN_M_COUNTRYNAME: "Япония",
IDS_YSM_BODY_VOL_M_VOLUME_ABB: "Vol",
IDS_YSM_HEADER_TV_AND_STB_ABB: "ТВ и STB",
IDS_YSM_OPT_SLEEP_M_RESERVATION_ABB: "Sleep"};
STMS.setStmsMap( map );
STMS.refreshAllStr();
});