WatchOnSandbox( "STMS", function( m ) {
var STMS = m.STMS,
map = {
IDS_ST_BODY_VOLUME_M_SOUND_ABB: "အသံအတုိးအက်ယ္",
IDS_SR_BODY_AIR_CONDITIONER: "ေလေအးေပးစက္",
IDS_SR_BODY_AUSTRIA_M_COUNTRYNAME: "ၾသစႀတီးယား",
IDS_SR_BODY_BELGIUM_M_COUNTRYNAME: "ဘယ္လ္ဂ်ီယမ္",
IDS_SR_BODY_CHINA_M_COUNTRYNAME: "တရုတ္ႏိုင္ငံ",
IDS_SR_BODY_DENMARK_M_COUNTRYNAME: "ဒိန္းမတ္",
IDS_SR_BODY_FAN_SPEED_DOWN: "ပန္ကာ အရွိန္ေလွ်ာ့ပါ",
IDS_SR_BODY_FAN_SPEED_UP: "ပန္ကာ အရွိန္ျမွင့္ပါ",
IDS_SR_BODY_FINLAND_M_COUNTRYNAME: "ဖင္လန္",
IDS_SR_BODY_FRANCE_M_COUNTRYNAME: "ျပင္သစ္",
IDS_SR_BODY_GERMANY_M_COUNTRYNAME: "ဂ်ာမနီ",
IDS_SR_BODY_IRELAND_M_COUNTRYNAME: "အိုက္ယာလန္",
IDS_SR_BODY_ITALY_M_COUNTRYNAME: "အီတလီ",
IDS_SR_BODY_LUXEMBOURG_M_COUNTRYNAME: "လူဇင္ဘာ့ဂ္",
IDS_SR_BODY_MODE: "အေနအထား",
IDS_SR_BODY_NORWAY_M_COUNTRYNAME: "ေနာ္ေဝ",
IDS_SR_BODY_POLAND_M_COUNTRYNAME: "ပိုလန္",
IDS_SR_BODY_PORTUGAL_M_COUNTRYNAME: "ေပၚတူဂီ",
IDS_SR_BODY_SET_UP: "တည္ေထာင္ပါ",
IDS_SR_BODY_SOUTH_KOREA_M_COUNTRYNAME: "ေတာင္ ကိုရီးယား",
IDS_SR_BODY_SPAIN_M_COUNTRYNAME: "စပိန္",
IDS_SR_BODY_SWEDEN_M_COUNTRYNAME: "ဆြီဒင္",
IDS_SR_BODY_SWITZERLAND_M_COUNTRYNAME: "ဆြစ္ဇာလန္",
IDS_SR_BODY_UNITED_KINGDOM_M_COUNTRYNAME: "ယူႏိုက္တက္ ကင္းဒန္း",
IDS_SR_BODY_UNITED_STATES_OF_AMERICA_M_COUNTRYNAME: "အေမရိကန္ ျပည္ေထာင္စု",
IDS_SR_BUTTON_BACK: "ေနာက္သို႔သြားပါ",
IDS_SR_BUTTON_CANCEL_ABB: "ပယ္ဖ်က္ပါ",
IDS_SR_BUTTON_DELETE: "ဖ်က္ပစ္ပါ",
IDS_SR_BUTTON_DONE: "ၿပီးပါၿပီ",
IDS_SR_BUTTON_EXIT: "ထြက္ပါ",
IDS_SR_BUTTON_INFO: "သတင္းအခ်က္အလက္",
IDS_SR_BUTTON_MENU: "စာရင္းဇယား",
IDS_SR_BUTTON_MUTE: "အသံတိတ္",
IDS_SR_BUTTON_OK: "အိုေက",
IDS_SR_BUTTON_POWER: "ပါဝါ",
IDS_SR_BUTTON_SELECT_YOUR_COUNTRY: "သင့္ ႏိုင္ငံ ေရြးပါ",
IDS_SR_BUTTON_SELECT_YOUR_COUNTRY_REGION: "သင့္ ႏိုင္ငံ/ေဒသ ေရြးပါ",
IDS_SR_BUTTON_SHOW_OTHER_BRANDS: "အျခား အမွတ္တံဆိပ္မ်ား ျပပါ",
IDS_SR_BUTTON_SOURCE_T_SMART_REMOTE: "မူရင္း",
IDS_SR_BUTTON_TEMP_DOWN_M_TEMPERATURE: "အပူခ်ိန္က်",
IDS_SR_BUTTON_TEMP_UP_M_TEMPERATURE: "အပူခ်ိန္တက္",
IDS_SR_BUTTON_TV: "တီဗြီ",
IDS_SR_BUTTON_YES: "ဟုတ္ကဲ့",
IDS_SR_HEADER_ALL_BRANDS: "ကုန္အမွတ္တံဆိပ္ အားလံုး",
IDS_SR_HEADER_DELETE_ABB: "ဖ်က္ပစ္ပါ",
IDS_SR_HEADER_RESET: "ျပန္စ",
IDS_SR_HEADER_WATCHON_M_APPLICATION: "WatchON",
IDS_SR_OPT_ADD_DEVICE_ABB: "ကိရိယာ ထည့္ပါ",
IDS_SR_OPT_STB_ABB: "STB",
IDS_YSM_POP_SET_UP_THE_REMOTE_CONTROL_ON_YOUR_DEVICE_Q: "သင့္ကိရိယာေပၚတြင္ အေဝးထိန္း တည္ေဆာက္မည္လား?",
IDS_YSM_OPT_SHOW_ALL_BRANDS_ABB: "အမွတ္တံဆိပ္ အားလံုး ျပပါ",
IDS_YSM_BUTTON_VOL_UC: "VOL",
IDS_YSM_BUTTON_CH: "CH",
IDS_YSM_BUTTON_NO: "မဟုတ္ပါ",
IDS_SAPPS_BODY_NOTICE: "သတိျပဳရန္",
IDS_MSGF_HEADER_OPTION: "Option",
IDS_MSGF_HEADER_OPTIONS: "ေရြးစရာမ်ား",
IDS_SSCHOL_HEADER_COMPLETED: "ျပီးပါျပီ",
IDS_YSM_HEADER_SET_UP_REMOTE_ABB: "အေ၀းထိန္းျခင္းကို တပ္ဆင္ျခင္း",
IDS_YSM_BODY_SET_UP_THE_REMOTE_CONTROL_ON_YOUR_DEVICE_Q: "သင့္ကိရိယာေပၚတြင္ အေဝးထိန္း တည္ေဆာက္မည္လား?",
IDS_YSM_BODY_LATIN_COUNTRIES_ABB: "လက္တင္ ႏိုင္ငံမ်ား",
IDS_YSM_BODY_POINT_YOUR_WATCH_TOWARDS_THE_PS_AND_TAP_THE_POWER_BUTTON: "%s သို႔ သင့္ နာရီကို ခ်ိန္ျပလိုက္ၿပီး ပါ၀ါခလုတ္ကို ႏွိပ္ပါ။",
IDS_YSM_BODY_TAP_THE_BUTTON_ABB: "ခလုတ္ကို ႏွိပ္ပါ။",
IDS_YSM_BODY_DID_IT_WORK_Q_ABB: "၎ အလုပ္လုပ္ခဲ့သလား?",
IDS_YSM_HEADER_SETUP_COMPLETE_ABB: "တပ္ဆင္ျခင္း ၿပီးပါၿပီ",
IDS_YSM_BODY_PS_REMOTE_CONTROL_SETUP_IS_COMPLETE: "%s အေ၀းထိန္းခလုတ္ တပ္ဆင္ျခင္း ၿပီးပါၿပီ။",
IDS_YSM_BODY_THIS_MODEL_IS_NOT_SUPPORTED: "ဤေမာ္ဒယ္ကို ပံ့ပိုးမႈ မေပးပါ။",
IDS_YSM_BODY_THE_REMOTE_CONTROL_WILL_BE_REMOVED: "အေ၀းထိန္းခလုတ္ကို ဖယ္ထုတ္ပါလိမ့္မည္။",
IDS_YSM_BODY_FAN_SPEED_ABB: "ပန္ကာ ျမန္ႏႈန္း",
IDS_YSM_BODY_MODE_ABB2: "အေနအထား",
IDS_YSM_OPT_AV_RECEIVER_ABB2: "AV လက္ခံစက္",
IDS_YSM_BODY_BLUE: "အျပာ",
IDS_YSM_BODY_CHANNEL_DOWN_ABB: "လိုင္း ဆင္းပါ",
IDS_YSM_BODY_CHANNEL_LIST_ABB: "လိုင္း စာရင္း",
IDS_YSM_BODY_CHANNEL_UP_ABB: "လိုင္း တက္ပါ",
IDS_YSM_BODY_DISK_MENU_ABB: "ဒစ္ မီႏူး",
IDS_YSM_BODY_DOWN: "က်",
IDS_YSM_BODY_DVR: "DVR",
IDS_YSM_BODY_EJECT_ABB: "ထုတ္ပါ",
IDS_YSM_BODY_FAST_FORWARD_ABB: "ေရွ႕သို႔ အျမန္ရစ္ပါ",
IDS_YSM_BODY_FAVOURITE_ABB: "စိတ္ၾကိဳက္",
IDS_YSM_BODY_FORMAT_HASPECT_ABB: "ေဖာ္မက္ (သြင္ျပင္)",
IDS_YSM_BODY_GREEN_ABB: "အစိမ္း",
IDS_YSM_BODY_HDMI_PD_ABB: "HDMI %d",
IDS_YSM_BODY_INPUT_ABB: "ျဖည့္သြင္း",
IDS_YSM_BODY_LEFT: "ဘယ္ဘက္",
IDS_YSM_BODY_LIST: "စာရင္း",
IDS_YSM_BODY_OTHER_COUNTRIES_ABB: "Other countries",
IDS_YSM_BODY_PAUSE: "ရပ္ထားပါ",
IDS_YSM_BODY_PLAY: "ဖြင့္ပါ",
IDS_YSM_BODY_PREVIOUS: "လြန္ခဲ့ေသာ",
IDS_YSM_BODY_PRE_CHANNEL_ABB: "ၾကိဳတင္ လိုင္း",
IDS_YSM_BODY_RED: "အနီ",
IDS_YSM_BODY_REWIND_ABB: "ျပန္ရစ္ပါ",
IDS_YSM_BODY_RIGHT_ABB2: "ညာ",
IDS_YSM_BODY_SELECT: "ေရြးခ်ယ္ပါ",
IDS_YSM_BODY_SOUND_MODE_ABB: "အသံ အေနအထား",
IDS_YSM_BODY_START_SETUP_OF_STB_REMOTE_CONTROL: "STB အေ၀းထိန္းခလုတ္ တပ္ဆင္ျခင္းကို စတင္ပါ။",
IDS_YSM_BODY_STOP: "ရပ္ပါ",
IDS_YSM_BODY_SUBTITLES_ABB2: "စာတန္းထိုးမ်ား",
IDS_YSM_BODY_SUBWOOFER_ABB: "ဆပ္ဝူဖာ",
IDS_YSM_BODY_SURROUND_ABB: "ဝန္းရံ",
IDS_YSM_BODY_TITLE_MENU_ABB: "ေခါင္းစဥ္ မီႏူး",
IDS_YSM_BODY_UP: "တက္ပါ",
IDS_YSM_BODY_YELLOW_ABB: "အဝါ",
IDS_YSM_BUTTON_CLEAR_HISTORY_ABB: "Clear history",
IDS_YSM_BUTTON_DONE: "ၿပီးပါၿပီ",
IDS_YSM_BUTTON_HISTORY: "ေနာက္ေၾကာင္း",
IDS_YSM_BUTTON_MENU: "စာရင္းဇယား",
IDS_YSM_BUTTON_NEXT: "ေနာက္ထပ္",
IDS_YSM_BUTTON_RETURN_UC: "RETURN",
IDS_YSM_BUTTON_SMART_HUB: "Smart Hub",
IDS_YSM_BUTTON_TOOLS_UC: "TOOLS",
IDS_YSM_BUTTON_VIDEO: "ဗြီဒီယို",
IDS_YSM_BUTTON_VOD: "VOD",
IDS_YSM_HEADER_HELP: "အကူအညီ",
IDS_YSM_OPT_0: "0",
IDS_YSM_OPT_1: "1",
IDS_YSM_OPT_2: "2",
IDS_YSM_OPT_3: "3",
IDS_YSM_OPT_4: "4",
IDS_YSM_OPT_5: "5",
IDS_YSM_OPT_6: "6",
IDS_YSM_OPT_7: "7",
IDS_YSM_OPT_8: "8",
IDS_YSM_OPT_9: "9",
IDS_YSM_OPT_ENTER: "ထည့္ပါ",
IDS_YSM_OPT_POWER: "ပါဝါ",
IDS_YSM_OPT_RECORD: "မွတ္တမ္းတင္ပါ",
IDS_YSM_OPT_VOLUME_DOWN: "အသံ ႏွိမ့္ပါ",
IDS_YSM_OPT_VOLUME_UP: "အသံ ျမွင့္ပါ",
IDS_YSM_TAB4_GUIDE: "လမ္းညႊန္",
IDS_CHATON_BODY_INDIA_M_COUNTRYNAME: "အိႏၵိယ",
IDS_CHATON_BODY_NETHERLANDS_M_COUNTRYNAME: "နယ္သာလန္",
IDS_WCL_BODY_RUSSIA_M_COUNTRYNAME: "႐ုရွား",
IDS_CHATON_BODY_AUSTRALIA_M_COUNTRYNAME: "ၾသစေၾတးလ်",
IDS_CHATON_BODY_SAUDI_ARABIA_M_COUNTRYNAME: "ေဆာ္ဒီ အာေရဗ်",
IDS_CHATON_BODY_CANADA_M_COUNTRYNAME: "ကေနဒါ",
IDS_CHATON_BODY_BRAZIL_M_COUNTRYNAME: "ဘရာဇီးလ္",
IDS_CHATON_BODY_MEXICO_M_COUNTRYNAME: "မကၠဆီကို",
IDS_CHATON_BODY_ARGENTINA_M_COUNTRYNAME: "အာဂ်င္တီးနား",
IDS_CHATON_BODY_CHILE_M_COUNTRYNAME: "ခ်ီလီ",
IDS_CHATON_BODY_PERU_M_COUNTRYNAME: "ပီရူး",
IDS_CHATON_BODY_COLOMBIA_M_COUNTRYNAME: "ကိုလန္ဘီယာ",
IDS_COM_POP_TRY_AGAIN: "ထပ္မံႀကိဳးစားပါ။",
IDS_YSM_BODY_CHANGE_DEVICE_M_NOUN_ABB: "ကိရိယာ ေျပာင္းပါ",
IDS_YSM_BODY_TEMP_M_TEMPERATURE_ABB: "ယာယီ",
IDS_MSGF_BODY_REMOTE: "အေဝး",
IDS_YSM_OPT_TEMP_DOWN_ABB: "အပူခ်ိန္ က်ဆင္းေနျခင္း",
IDS_YSM_OPT_TEMP_UP_ABB: "အပူခ်ိန္ တက္လာျခင္း",
IDS_YSM_OPT_TURBO_ABB: "တာဘို",
IDS_YSM_OPT_DISPLAY_ABB: "ျပသမႈ",
IDS_YSM_OPT_DELIMITER_ABB: "ေဒတာ အစႏွင့္အဆုံး သေကၤတ",
IDS_YSM_OPT_INTERNET_ABB: "အင္တာနက္",
IDS_YSM_OPT_PIP: "PiP",
IDS_YSM_OPT_PIP_SWAP_ABB: "PiP ဖလွယ္ျခင္း",
IDS_YSM_OPT_PIP_CHANNEL_MINUS_ABB: "PiP ခ်ာနယ္ -",
IDS_YSM_OPT_PIP_CHANNEL_PLUS_ABB: "PiP ခ်ာနယ္ +",
IDS_YSM_OPT_PIP_MOVE_ABB: "PiP ေရႊ႕ျခင္း",
IDS_YSM_OPT_DTV: "DTV",
IDS_YSM_OPT_COMPONENT_PD_ABB: "%d အစိတ္အပိုင္း",
IDS_YSM_OPT_USB: "USB",
IDS_YSM_OPT_PICTURE_ABB2: "ပုံ",
IDS_YSM_OPT_3D: "3D",
IDS_YSM_OPT_REPLAY_ABB: "ခ်က္ခ်င္း ျပန္ဖြင့္ျခင္း",
IDS_YSM_OPT_DAY_MINUS: "ေန႔ -",
IDS_YSM_OPT_DAY_PLUS: "ေန႔ +",
IDS_YSM_OPT_RADIO: "ေရဒီယုိ",
IDS_YSM_OPT_TV_RADIO_ABB: "TV/ေရဒီယို",
IDS_YSM_OPT_SWING_DOWN_ABB: "ေအာက္သို႔ လႊဲရိုက္ျခင္း",
IDS_YSM_OPT_SWING_LEFT_ABB: "ဘယ္သို႔ လႊဲရိုက္ျခင္း",
IDS_YSM_OPT_SWING_RIGHT_ABB: "ညာသို႔ လႊဲရိုက္ျခင္း",
IDS_YSM_OPT_SWING_UP_ABB: "အေပၚသို႔ လႊဲရိုက္ျခင္း",
IDS_YSM_OPT_PVR_MENU_ABB: "PVR မီႏူး",
IDS_YSM_OPT_RETURN_TO_LIVE_ABB: "တိုက္ရိုက္အစီအစဥ္သို႔ ျပန္သြားပါ",
IDS_YSM_OPT_POWER_OFF_ABB2: "ပါ၀ါ ပိတ္ထားသည္",
IDS_YSM_OPT_POWER_ON_ABB: "ပါ၀ါ ဖြင့္ထားသည္",
IDS_CHATON_BODY_JAPAN_M_COUNTRYNAME: "ဂ်ပန္",
IDS_YSM_BODY_VOL_M_VOLUME_ABB: "အသံအတုိးအက်ယ္",
IDS_YSM_HEADER_TV_AND_STB_ABB: "TV ႏွင့္ STB",
IDS_YSM_OPT_SLEEP_M_RESERVATION_ABB: "အိပ္ပါ"};
STMS.setStmsMap( map );
STMS.refreshAllStr();
});