var TESTS = {
	"testPages":[
		// Put your test here
		"autodividers",
		"button",
		"check",
		"controlbar",
		"datetimepicker",
		"dayselector",
		"expandablelist",
		"extendablelist",
		"handler",
		"gallery",
		"multimediaview",
		"navigationbar",
		"nocontents",
		"notification",
		"pagecontrol",
		"popupwindow",
		"popupwindow_ctxpopup",
		"progressbar",
		"radio",
		"searchbar",
		"segmentcontrol",
		"shortcutscroll",
		"slider",
		"swipelist",
		"toggleswitch",
		"tokentextarea",
		"virtuallist",
		"virtualgrid",
		"collapsible"
	]
};
