var TESTS = {
	"testPages":[
		// Put your test here
		"button",
		"check",
		"tabbar",
		"datetimepicker",
		"extendablelist",
		"handler",
		"gallery",
		"gallery3d",
		"multimediaview",
		"navigationbar",
		"notification",
		"popupwindow",
		"popupwindow_ctxpopup",
		"progressbar",
		"progress",
		"radio",
		"searchbar",
		"segmentcontrol",
		"fastscroll",
		"slider",
		"swipe",
		"tokentextarea",
		"virtuallist",
		"virtualgrid",
		"collapsible",
		"page"
	]
};
